### ISSUE TITLE
"Published Date" is 	Invalid date

### ISSUE THREAD

**Issue by hideokamoto** [getshifter/BugReport#3]
## Kind of the feature

"Published Date" shows Invalid date

![Invalid date](https://s3.amazonaws.com/tmpfiles-for-dc/github-issues/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88+2016-11-04+17.25.16.png "invalid1")

![Invalid date](https://s3.amazonaws.com/tmpfiles-for-dc/github-issues/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88+2016-11-04+17.28.55.png "invalid2")

![Invalid date](https://s3.amazonaws.com/tmpfiles-for-dc/github-issues/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88+2016-11-04+17.31.54.png "invalid3")

## Expected behavior and actual behavior.
Should be show Date.
Like "November 4Th 2016, 4:35:36 pm"

## Steps to reproduce the bug.

- Access Shifter Dashboard
- go to `Project Detail` page
- click `generate now` button
- check ` Generate Histroy`

**Comment by horike37** [comment]
fixed.
時刻の型変換が2重で実施されている部分がありました。
そのため、Invalidとなっていたようです
