### ISSUE TITLE
Unable to create new project

### ISSUE THREAD

**Issue by ithardeep** [getshifter/BugReport#4]
## Kind of the feature
Add New Project

Project, Import, WP-CLI Shifter or others.

## Expected behavior and actual behavior.
Expected behavior "Should Show New Screen" Actual behavior "GETTING ERROR MESSAGE"

## Steps to reproduce the bug.
Login, from the home screen chose New Project and you should get following error
http://i.imgur.com/qsD4FTq.png

## Additional Data(Optional)
username - hardeep
* *** `Published URL` or `site id`
* *** WordPress version (if you imported archive.)
* *** php version

**Comment by horike37** [comment]
@ithardeep 
Thank you foy your report!
Clould you  tell us what kind of brower and the OS and version?

**Comment by ithardeep** [comment]
Sure,
I was using google chrome with following version
http://i.imgur.com/EErRsNY.png

OS, using windows 8.1

**Comment by horike37** [comment]
@ithardeep 
We fixed this bug and just released.
Thank you for great help!!

**Comment by ithardeep** [comment]
Thanks for fix!
