### ISSUE TITLE
Unable to do comment 

### ISSUE THREAD

**Issue by ithardeep** [getshifter/BugReport#5]
After publishing site, when I did some testing and found it works really fast !
but unfortunately I am not able to do comment :(

When ever I do comment I got following error
http://i.imgur.com/lb2F4L5.png

**Comment by plastikdreams** [comment]
Hi, ithardeep, thank you for using our service and your report!

Our service, Shifter doesn't support comment feature so that we recommend to use Disqus, Facebook's comment or other commenting services.

Thank you again for your report.

**Comment by ithardeep** [comment]
Hmm, getshifter is really a good product and you guys have put lot of efforts and precious time to make this product more cool and it really is.

According to the reply, it seems like shifter currently does not support any form submission. This may divide your customers into two parts, blog user and business sites

The users who have simple blog and comment, they can use your services but think about business wordpress sites they need lot of user inputs like internal email subscription, contact us form, checkout system etc.

They need to communicate with database otherwise shifter would not be option for them.
Hope you guys found a way to communicate form with server side, if you able to do this, then lot of people can enjoy fast speed with form submission!

**Comment by plastikdreams** [comment]
Thank you for your suggestions.

Of course, we understand that many users want to use a built-in comment system, but we think external comment systems (e.g. Jetpack, facebook, google+ and Disqus) is high-performance and will satisfy most of the users' need, so that we recommend to use them. 

Thank you again your feedback.
