### ISSUE TITLE
Accessible via http & https

### ISSUE THREAD

**Issue by AtsushiA** [getshifter/BugReport#6]
## Kind of the feature
others.

## Expected behavior and actual behavior.

Then Attach Domain.
Accessible via http & https (http://www.example.com / https://www.example.com)
I want you to be able to select http/https or redirect "https"

## Steps to reproduce the bug.

not bug

**Comment by sawanoboly** [comment]
Thank you for suggesting features 😃  We will consider it.

**Comment by sawanoboly** [comment]
@AtsushiA 
https://getshifter.zendesk.com/hc/en-us/articles/115000171567

As a result of consideration, redirect to HTTPS was set as the default setting. Thanks 👍
