### ISSUE TITLE
unable "Start App"

### ISSUE THREAD

**Issue by AtsushiA** [getshifter/BugReport#7]
## Kind of the feature

Shifter

## Steps to reproduce the bug.

Push "Start App" btn

## Additional Data(Optional)

Generate History  
Status : fail
Message : Request timed out.
<img width="1098" alt="screen shot 2016-12-07 at 19 27 03" src="https://cloud.githubusercontent.com/assets/5989338/20964245/107159b2-bcb4-11e6-9a0c-119f0cbd7c01.png">

**Comment by horike37** [comment]
@AtsushiA 
Thank you for reporting!
We noticed it and repairing now. 
We are sorry but please wait a little more

**Comment by horike37** [comment]
@AtsushiA
Solved the problem.
We want you to try it again

**Comment by AtsushiA** [comment]
@horike37 
I confirmed what was fixed
Thank you!!
